name: Detect Logging in Custom Extractor

on:
  pull
  push:
    branches: ["master", "main"]
    paths:
      - 'house-spiders/**'
jobs:
  detect-logging:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Filter for house-spider changes
      uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          housespiders:
            - 'house-spiders/**/*.py'
            
    - name: Detect print statements
      run: |
        if grep -rn "print" --include='*.py' .; then
          echo "Print statements found!"
          exit 1
        fi

    - name: Detect file statements
      run: |
        if grep -rn "with open" --include='*.py' .; then
          echo "logging into file statements found!"
          exit 1
        fi
