name: Detect Logging in Custom Extractor

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  detect-logging:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Detect print statements
      run: |
        if grep -rn "print" --include='*.py' .; then
          echo "print statements found!"
          exit 1
        fi
    - name: Detect file statements
      run: |
        if grep -rn "with open" --include='*.py' .; then
          echo "print statements found!"
          exit 1
        fi
