name: Detect Logging in Custom Extractor

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  detect-logging:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Filter for house-spider changes
      uses: dorny/paths-filter@v3
      id: changes
      with:
        filters: |
          housespiders:
            - 'house-spiders/**/*.py'
            
    - name: Detect print statements
      run: |
        if grep -rn --include='*.py' 'print|open' .; then
          echo "Print or logging statements found!"
          exit 1
        fi
      shell: bash